bin: Add support for running parts of update-ips
It's now possible to run update-ips with the flags --enable and
--disable.

The --enable flag will run only the operation that you supply it,
it can be repeated.

The --disable flag will run all operations except the one you supply,
it can be repeated.

Not using either of the flags will run all the operations and will
work as before except that things will be running in a different
order. Functionally there should not be any difference.

diff --git a/bin/ck8s b/bin/ck8s
--- a/bin/ck8s
+++ b/bin/ck8s
@@ -10,36 +10,38 @@ source "${here}/common.bash"
 
 usage() {
   echo "COMMANDS:" 1>&2
-  echo "  apply <wc|sc> [--sync] [--concurrency=<num>]    deploy the apps" 1>&2
-  echo "  clean <wc|sc>                                   Cleans the cluster of apps" 1>&2
-  echo "  completion <bash|fish>                          output shell completion code for bash/fish" 1>&2
-  echo "  diagnostics <wc|sc> [--help]                    Runs diagnostics of apps" 1>&2
-  echo "  dry-run <wc|sc> [--kubectl]                     runs helmfile diff" 1>&2
-  echo "  explain <config|secrets> [key.to.parameter]     explains the config or secrets" 1>&2
-  echo "  fix-psp-violations <wc|sc>                      Checks and restarts pods that violates Pod Security Polices, applicable for new environments" 1>&2
-  echo "  flavors                                         lists supported configuration flavors" 1>&2
-  echo "  init <wc|sc|both> [--generate-new-secrets]      initialize the config path" 1>&2
-  echo "  install-requirements [--user] [--no-pass]       installs or updates required tools to run compliantkubernetes-apps" 1>&2
-  echo "  k8s-installers                                  lists supported kubernetes installers" 1>&2
-  echo "  kubeconfig <user|dev|admin>                     generate user kubeconfig, stored at CK8S_CONFIG_PATH/user" 1>&2
-  echo "  ops helm <wc|sc>                                run helm as cluster admin" 1>&2
-  echo "  ops helmfile <wc|sc>                            run helmfile as cluster admin" 1>&2
-  echo "  ops kubecolor <wc|sc>                           run kubecolor as cluster admin" 1>&2
-  echo "  ops kubectl <wc|sc>                             run kubectl as cluster admin" 1>&2
-  echo "  ops velero <wc|sc>                              run velero as cluster admin" 1>&2
-  echo "  providers                                       lists supported cloud providers" 1>&2
-  echo "  s3cmd [cmd]                                     run s3cmd" 1>&2
-  echo "  team add-pgp <fp>                               add a new PGP key to secrets" 1>&2
-  echo "  team remove-pgp <fp>                            remove a PGP key from secrets and rotate the data encryption key" 1>&2
-  echo "  test <wc|sc> [--logging-enabled]                test the applications" 1>&2
-  echo "  update-ips <wc|sc|both> <apply|dry-run>         Automatically fetches and applies the IPs for network policies" 1>&2
-  echo "  upgrade <wc|sc|both> <vX.Y> apply [--dry-run]   runs all apply steps upgrading the environment" 1>&2
-  echo "  upgrade <wc|sc|both> <vX.Y> prepare             runs all prepare steps upgrading the configuration" 1>&2
-  echo "  upgrade <wc|sc|both> unlock                     reset an upgrade to allow trying again" 1>&2
-  echo "  validate <wc|sc>                                validates config files" 1>&2
-  echo "  check-requirements                              check the locally installed tool versions" 1>&2
-  echo "  harbor-restore [--backup-id <value>] [--azure-rclone-fixup]   restores Harbor using detected storage type" 1>&2
-  echo "  version <all|both|config|sc|wc>                 shows apps version" 1>&2
+  echo "  apply <wc|sc> [--sync] [--concurrency=<num>]                 deploy the apps" 1>&2
+  echo "  clean <wc|sc>                                                clean the cluster of apps" 1>&2
+  echo "  completion <bash|fish>                                       output shell completion code for bash/fish" 1>&2
+  echo "  diagnostics <wc|sc> [--help]                                 run diagnostics of apps" 1>&2
+  echo "  dry-run <wc|sc> [--kubectl]                                  run helmfile diff" 1>&2
+  echo "  explain <config|secrets> [key.to.parameter]                  explain the config or secrets" 1>&2
+  echo "  fix-psp-violations <wc|sc>                                   check and restarts pods that violates Pod Security Polices, applicable for new environments" 1>&2
+  echo "  flavors                                                      list supported configuration flavors" 1>&2
+  echo "  init <wc|sc|both> [--generate-new-secrets]                   initialize the config path" 1>&2
+  echo "  install-requirements [--user] [--no-pass]                    install or update required tools to run compliantkubernetes-apps" 1>&2
+  echo "  k8s-installers                                               list supported kubernetes installers" 1>&2
+  echo "  kubeconfig <user|dev|admin>                                  generate user kubeconfig, stored at CK8S_CONFIG_PATH/user" 1>&2
+  echo "  ops helm <wc|sc>                                             run helm as cluster admin" 1>&2
+  echo "  ops helmfile <wc|sc>                                         run helmfile as cluster admin" 1>&2
+  echo "  ops kubecolor <wc|sc>                                        run kubecolor as cluster admin" 1>&2
+  echo "  ops kubectl <wc|sc>                                          run kubectl as cluster admin" 1>&2
+  echo "  ops velero <wc|sc>                                           run velero as cluster admin" 1>&2
+  echo "  providers                                                    list supported cloud providers" 1>&2
+  echo "  s3cmd [cmd]                                                  run s3cmd" 1>&2
+  echo "  team add-pgp <fp>                                            add a new PGP key to secrets" 1>&2
+  echo "  team remove-pgp <fp>                                         remove a PGP key from secrets and rotate the data encryption key" 1>&2
+  echo "  test <wc|sc> [--logging-enabled]                             test the applications" 1>&2
+  echo "  update-ips <wc|sc|both> apply [--enable op] [--disable op]   discover and apply network policy configuration changes" 1>&2
+  echo "  update-ips <wc|sc|both> dry-run [--enable op] [--disable op] discover and print network policy configuration changes" 1>&2
+  echo "  update-ips <wc|sc|both> operations                           list operations that can be enabled or disabled when discovering network policy changes" 1>&2
+  echo "  upgrade <wc|sc|both> <vX.Y> apply [--dry-run]                run all apply steps upgrading the environment" 1>&2
+  echo "  upgrade <wc|sc|both> <vX.Y> prepare                          run all prepare steps upgrading the configuration" 1>&2
+  echo "  upgrade <wc|sc|both> unlock                                  reset an upgrade to allow trying again" 1>&2
+  echo "  validate <wc|sc>                                             validate config files" 1>&2
+  echo "  check-requirements                                           check the locally installed tool versions" 1>&2
+  echo "  harbor-restore [--backup-id <value>] [--azure-rclone-fixup]  restore Harbor using detected storage type" 1>&2
+  echo "  version <all|both|config|sc|wc>                              show apps version" 1>&2
   exit 1
 }
 
@@ -47,7 +49,6 @@ SYNC=""
 KUBECTL=""
 GEN_NEW_SECRETS=""
 CONCURRENCY="--concurrency=8"
-CK8S_IPV6_ENABLED="false"
 
 for arg in "${@}"; do
   case "${arg}" in
@@ -55,7 +56,6 @@ for arg in "${@}"; do
   "--kubectl") KUBECTL="kubectl" ;;
   "--generate-new-secrets") GEN_NEW_SECRETS="--generate-new-secrets" ;;
   "--concurrency="*) CONCURRENCY="${arg}" ;;
-  "--ipv6") CK8S_IPV6_ENABLED="true" ;;
   esac
 done
 
@@ -147,8 +147,11 @@ explain)
   ;;
 update-ips)
   [[ "${2}" =~ ^(wc|sc|both)$ ]] || usage
-  [[ "${3}" =~ ^(apply|dry-run)$ ]] || usage
-  "${here}/update-ips.bash" "${2}" "${3}" "${CK8S_IPV6_ENABLED}"
+  [[ "${3}" =~ ^(apply|dry-run|operations)$ ]] || usage
+  cluster="${2}"
+  command="${3}"
+  shift 3
+  "${here}/update-ips.bash" "${cluster}" "${command}" "${@}"
   ;;
 fix-psp-violations)
   [[ "${2}" =~ ^(wc|sc)$ ]] || usage
